/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_hellojni_nativeCode */

#ifndef _Included_com_android_hellojni_nativeCode
#define _Included_com_android_hellojni_nativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_hellojni_nativeCode
 * Method:    myAdd
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_android_hellojni_nativeCode_myAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_android_hellojni_nativeCode
 * Method:    myAdd1
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_android_hellojni_nativeCode_myAdd1
  (JNIEnv *, jobject);

/*
 * Class:     com_android_hellojni_nativeCode
 * Method:    writemes
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_android_hellojni_nativeCode_writemes
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_android_hellojni_nativeCode
 * Method:    myAdd2
 * Signature: ([F)D
 */
JNIEXPORT jdouble JNICALL Java_com_android_hellojni_nativeCode_myAdd2
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_android_hellojni_nativeCode
 * Method:    myAdd3
 * Signature: ([F)D
 */
JNIEXPORT jdouble JNICALL Java_com_android_hellojni_nativeCode_myAdd3
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
