/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_hellojni_HelloJniTestActivity */

#ifndef _Included_com_android_hellojni_HelloJniTestActivity
#define _Included_com_android_hellojni_HelloJniTestActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_hellojni_HelloJniTestActivity_MODE_PRIVATE
#define com_android_hellojni_HelloJniTestActivity_MODE_PRIVATE 0L
#undef com_android_hellojni_HelloJniTestActivity_MODE_WORLD_READABLE
#define com_android_hellojni_HelloJniTestActivity_MODE_WORLD_READABLE 1L
#undef com_android_hellojni_HelloJniTestActivity_MODE_WORLD_WRITEABLE
#define com_android_hellojni_HelloJniTestActivity_MODE_WORLD_WRITEABLE 2L
#undef com_android_hellojni_HelloJniTestActivity_MODE_APPEND
#define com_android_hellojni_HelloJniTestActivity_MODE_APPEND 32768L
#undef com_android_hellojni_HelloJniTestActivity_BIND_AUTO_CREATE
#define com_android_hellojni_HelloJniTestActivity_BIND_AUTO_CREATE 1L
#undef com_android_hellojni_HelloJniTestActivity_BIND_DEBUG_UNBIND
#define com_android_hellojni_HelloJniTestActivity_BIND_DEBUG_UNBIND 2L
#undef com_android_hellojni_HelloJniTestActivity_BIND_NOT_FOREGROUND
#define com_android_hellojni_HelloJniTestActivity_BIND_NOT_FOREGROUND 4L
#undef com_android_hellojni_HelloJniTestActivity_CONTEXT_INCLUDE_CODE
#define com_android_hellojni_HelloJniTestActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_android_hellojni_HelloJniTestActivity_CONTEXT_IGNORE_SECURITY
#define com_android_hellojni_HelloJniTestActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_android_hellojni_HelloJniTestActivity_CONTEXT_RESTRICTED
#define com_android_hellojni_HelloJniTestActivity_CONTEXT_RESTRICTED 4L
#undef com_android_hellojni_HelloJniTestActivity_RESULT_CANCELED
#define com_android_hellojni_HelloJniTestActivity_RESULT_CANCELED 0L
#undef com_android_hellojni_HelloJniTestActivity_RESULT_OK
#define com_android_hellojni_HelloJniTestActivity_RESULT_OK -1L
#undef com_android_hellojni_HelloJniTestActivity_RESULT_FIRST_USER
#define com_android_hellojni_HelloJniTestActivity_RESULT_FIRST_USER 1L
#undef com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_DISABLE
#define com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_DIALER
#define com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_DIALER 1L
#undef com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_SHORTCUT
#define com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_android_hellojni_HelloJniTestActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_android_hellojni_HelloJniTestActivity
 * Method:    myAdd
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_android_hellojni_HelloJniTestActivity_myAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_android_hellojni_HelloJniTestActivity
 * Method:    myAdd1
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_android_hellojni_HelloJniTestActivity_myAdd1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
