/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_WangTest_nativeCode */

#ifndef _Included_com_android_WangTest_nativeCode
#define _Included_com_android_WangTest_nativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_WangTest_nativeCode
 * Method:    ProcessG2Byte
 * Signature: ([BII[B[F[D)B
 */
JNIEXPORT jbyte JNICALL Java_com_android_WangTest_nativeCode_ProcessG2Byte
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jfloatArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
